# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll', models.IntegerField(max_length=10)),
                ('cls', models.CharField(max_length=50)),
            ],
        ),
    ]
